import React, {Component} from 'react';
import {View, Text, Modal, StyleSheet, Linking} from 'react-native';
import {FlatGrid} from 'react-native-super-grid';
import {Image} from 'react-native-elements';
import TipsSwiper from './tips-swiper';
import {Directions, TouchableOpacity} from 'react-native-gesture-handler';
import {Button} from 'react-native-elements';
import {italic} from 'ansi-colors';
import {COLORS} from '../../utils/constants';

class Tips extends Component {
  state = {
    modalVisible: false,
  };

  setModalVisible = visible => {
    this.setState({modalVisible: visible});
  };

  getSelectedTips = () => {
    return JSON.parse(
      '[{"id":1,"tip_cat_id":3,"name":"Apples","description":"Apples ripen 6-10x faster at room temp. Store them in the fridge and they’ll be at their best for 6 weeks","img_url":""},{"id":2,"tip_cat_id":3,"name":"Tomatoes","description":"Store fresh tomatoes on the counter away from direct sunlight with the stem up. Refrigeration can cause loss of sweetness and texture.","img_url":""},{"id":3,"tip_cat_id":3,"name":"Letuce","description":"Salad greens are at their best for up to 5 days longer when properly stored in a hard-sided container lined with paper towels.","img_url":""},{"id":4,"tip_cat_id":3,"name":"Flour","description":"Flour stays fresh in the fridge for 2 years vs. just 1 in the pantry. Got extra four? Make cookie dough. You can freeze it for 3 months and bake it for a treat!","img_url":""},{"id":5,"tip_cat_id":3,"name":"Basil","description":"Basil lasts the longest on the counter","img_url":""},{"id":6,"tip_cat_id":3,"name":"Nuts","description":"Nuts are best stored in the refrigerator once a package is opened as it keeps their oils fresher!","img_url":""},{"id":7,"tip_cat_id":3,"name":"Avocados","description":"Store avocados on the counter until ripe","img_url":""},{"id":8,"tip_cat_id":3,"name":"Bread","description":"Bread is at its best for up to 6 months in the freezer","img_url":""},{"id":9,"tip_cat_id":3,"name":"Beef","description":"When frozen raw and kept in the freezer","img_url":""},{"id":10,"tip_cat_id":3,"name":"Lefovers","description":"Lefovers are best stored in a clear","img_url":""},{"id":11,"tip_cat_id":3,"name":"Eggs","description":"Eggs past their sell-by date? Don’t toss them","img_url":""},{"id":12,"tip_cat_id":1,"name":"Laptop","description":"A plugged-in","img_url":""},{"id":13,"tip_cat_id":1,"name":"Microwave","description":"The average American household could save $165 on their electricity bill each year by unplugging idle devices.","img_url":""},{"id":14,"tip_cat_id":1,"name":"TV","description":"You might not think of it","img_url":""},{"id":15,"tip_cat_id":1,"name":"Gaming console","description":"When you’re done playing video games","img_url":""},{"id":16,"tip_cat_id":1,"name":"Charger","description":"Plug your chargers into a power strip or smar outlet","img_url":""},{"id":17,"tip_cat_id":1,"name":"Washing machine","description":"American households’ idle energy use is the equivalent of the energy generated by 50 large power plants in a year.","img_url":""},{"id":18,"tip_cat_id":2,"name":"Hose","description":"If your garden hose leaks","img_url":""},{"id":19,"tip_cat_id":2,"name":"Faucet","description":"A drip every 2 seconds equals over 1","img_url":""},{"id":20,"tip_cat_id":2,"name":"Dishwasher","description":"Fixing household water leaks could save you up to 10% on your water bill.","img_url":""},{"id":21,"tip_cat_id":2,"name":"Toilet","description":"Spot toilet leaks by puting a drop of food coloring in your toilet tank. If there is color in the bowl afer 10 minutes","img_url":""},{"id":22,"tip_cat_id":2,"name":"Pipes","description":"Check your water meter before and afer going 2 hours without using water. If it changes","img_url":""},{"id":23,"tip_cat_id":4,"name":"Own","description":"High-quality items","img_url":""},{"id":24,"tip_cat_id":4,"name":"Rent Dress","description":"Remember that occasion-specifc dress or suit you’ve only worn once? Next time instead of having it collect dust in your closet","img_url":""},{"id":25,"tip_cat_id":4,"name":"Rent Drill","description":"There are 80 million power drills in America that are used an average of 13 minutes. Instead of purchasing a tool that you will use once a month","img_url":""},{"id":26,"tip_cat_id":4,"name":"Repair Cloths","description":"Just because the zipper is broken on your favorite jacket doesn’t mean you need to toss it! Easily repair high-quality clothing with a quick trip to the tailor","img_url":""},{"id":27,"tip_cat_id":4,"name":"Repair Furniture","description":"Give old furniture a tune-up. Tighten up loose legs","img_url":""},{"id":28,"tip_cat_id":4,"name":"Donate","description":"Want to tidy up your closet? Get rid of items that don’t give you joy and donate them to your local thrif shop. Enjoy the thrill of knowing someone else will be able to get use out of your item.","img_url":""},{"id":29,"tip_cat_id":4,"name":"Shoes","description":"Own items that you no longer want or ft into? Resell them to your local consignment shop or with an app. You’ll get some extra cash and the knowledge that someone else will fall in love them.","img_url":""},{"id":30,"tip_cat_id":4,"name":"Mobile","description":"Keeping your cell phone and other electronics can help save resources and help you make a proft. Cash in afer keeping your phone for 2 years.","img_url":""},{"id":31,"tip_cat_id":4,"name":"Water Bottle","description":"Switch to a reusable water botle instead of single-use plastic botles to help the planet Rent and stay hydrated.","img_url":""},{"id":32,"tip_cat_id":4,"name":"Reuse","description":"Have a favorite t-shir that has more holes than sleeves? Take it to a clothing retailer that collects worn clothes to make them into new ones.","img_url":""}]',
    );
  };

  onItemClick = () => {
    this.setModalVisible(true);
  };

  render() {
    const items = [
      {
        name: 'ENERGY',
        code: COLORS.PRIMARY_BG,
        img: require('../../images/energy.png'),
      },
      {name: 'FOOD', code: COLORS.PRIMARY_BG, img: require('../../images/food.png')},
      {name: 'WATER', code: COLORS.PRIMARY_BG, img: require('../../images/water.png')},
      {name: 'STUFF', code: COLORS.PRIMARY_BG, img: require('../../images/stuff.png')},
    ];
    return (
      <View style={{alignItems: 'center'}}>
        <Text style={styles.pageDesc}>{'Your Plan,\n     Your Planet'}</Text>
        <FlatGrid
          itemDimension={130}
          items={items}
          style={styles.gridView}
          // staticDimension={300}
          // fixed
          // spacing={20}
          renderItem={({item, index}) => (
            <TouchableOpacity onPress={() => this.onItemClick()}>
              <View
                style={[styles.itemContainer, {backgroundColor: item.code}]}>
                <View style={{alignItems: 'center'}}>
                  <Image
                    source={item.img} // TODO::dynamic image
                    style={{width: 150, height: 150}}
                  />
                </View>
                <Text style={styles.itemName}>{item.name}</Text>
              </View>
            </TouchableOpacity>
          )}
        />

        {this.state.modalVisible && (
          <Modal
            animationType="slide"
            transparent
            visible={this.state.modalVisible}
            onRequestClose={() => {
              Alert.alert('Modal has been closed.');
            }}>
            <TipsSwiper
              setModalVisible={this.setModalVisible}
              selectedSourceColor={COLORS.TIPS_BG} // TODO:: make this dynamic
              tips={this.getSelectedTips()} // TODO:: make this dynamic
            />
          </Modal>
        )}

        <Text
          style={styles.itemCode}
          onPress={() =>
            Linking.openURL('http://www.carbonfootprint.com/calculator.aspx')
          }>
          {'Calculate how big is your carbon footprint!!'}
        </Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  gridView: {
    marginTop: 20,
    flex: 1,
  },
  itemContainer: {
    justifyContent: 'flex-end',
    borderRadius: 5,
    padding: 10,
    height: 200,
  },
  itemName: {
    fontSize: 16,
    color: COLORS.SECONDARY_TEXT,
    fontWeight: '600',
  },
  itemCode: {
    fontWeight: '600',
    fontSize: 16,
    color: 'blue',
    marginTop: 20,
  },

  pageDesc: {
    fontSize: 40,
    color: '#545454',
    marginTop: 20,
    paddingHorizontal: 30,
    fontWeight: '600',
    fontFamily: 'CormorantGaramond-BoldItalic',
  },
});

export default Tips;
